name: load-testing-workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  api-test:
    uses: nelson1234567890/pipeline-reusable-kata/.github/workflows/reusable.yml@master
    with:
      java-version: "21"
      command-execute: "mvn gatling:test"
      path-report: "target/gatling/"

