name: load-testing-integration

on:
  push:
    branches:
      - staging
      - master
      - Feature/*
      - feature/*
  workflow_dispatch:

jobs:
  integration-load-tests:
    uses: bancodebogota/bbog-dig-do-testing-pipeline/.github/workflows/test_load_integration.yml@v2
    with:
      environment: st
      command-install: 'mvn clean install -DskipTests'
      command-execute: 'mvn test -P load'
      repository: 'bbog-bnpl-cp-load-testing'
      files-to-export: >
        report/**
      dependencies-file-cache: '**/pom.xml'
      folder-libraries-cache: '~/.m2'
      name-file-report: 'results'
      prefix-team: 'AE-CP'
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
