name: load-testing-integration

on:
  push:
    branches:
      - staging
      - master
  workflow_dispatch:

jobs:
  integration-load-tests:
    uses: bancodebogota/bbog-dig-do-testing-pipeline/.github/workflows/test_load_integration.yml@v6
    with:
      environment: st
      aws-region: "us-east-1"
      command-install: 'mvn clean install -DskipTests'
      command-execute: 'mvn gatling:test'
      java-version: "17"
      use-aws-credentials: false
      dependencies-file-cache: '**/pom.xml'
      folder-libraries-cache: '~/.m2'
      files-to-export: target/gatling
      name-file-report: 'index.html'
      prefix-team: 'AE-CP'
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
